[project]
name = "k-pldi-tutorial"
version = "0.1.0"
source = "k-src"

[targets.arithmetic]
backend = "llvm"
main-file = "arithmetic.k"

[targets.arithmetic-eval]
backend = "llvm"
main-file = "arithmetic-eval.k"
syntax-module = "ARITHMETIC-SYNTAX"
