[project]
name = "k-pldi-tutorial"
version = "0.1.0"
source = "k-src"

[targets.llvm]
backend = "llvm"
main-file = "imp.md"
syntax-module = "IMP-SYNTAX"
gen-bison-parser = true

[targets.haskell]
backend = "haskell"
main-file = "imp.md"
syntax-module = "IMP-SYNTAX"
