name: 'Update Version'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/pyk'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-versions:
    name: 'Update pyk version'
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: 'Install Nix'
        uses: cachix/install-nix-action@v20
        with:
          # Keep nix at <=2.7 https://github.com/NixOS/nix/issues/6572
          # but >= 2.4 due to ZSTD compression done by cachix >=1.1 https://blog.cachix.org/posts/2022-12-19-zstd-compression/
          install_url: https://releases.nixos.org/nix/nix-2.7.0/install
          extra_nix_config: |
            substituters = http://cache.nixos.org https://cache.iog.io
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
      - name: 'Install Cachix'
        uses: cachix/cachix-action@v10
        with:
          name: k-framework
          authToken: '${{ secrets.CACHIX_PUBLIC_TOKEN }}'
      - name: 'Install Poetry'
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.3.2
          echo ${HOME}/.local/bin >> $GITHUB_PATH
      - name: 'Update pyk release tag'
        run: |
          PYK_VERSION=$(cat ./deps/pyk_release)
          sed -i 's!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag = "[v0-9\.]*" }!pyk = { git = "https://github.com/runtimeverification/pyk.git", tag = "'${PYK_VERSION}'" }!' pyproject.toml
          poetry update
          git add pyproject.toml poetry.lock
          git commit -m '{pyproject.toml,poetry.lock}: sync Poetry files' || true
      - name: 'Update Nix flake inputs'
        run: |
          nix --extra-experimental-features 'nix-command flakes' --show-trace flake update
          git add flake.nix flake.lock
          git commit -m 'flake.{nix,lock}: update Nix derivations' || true
      - name: 'Push updates'
        run: git push
